name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: PP1_1_test.java
      id: pp1_1_test-java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: PP1_1_test.java
        setup-command: javac PP1_1.java
        command: gradle test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PP1_1_TEST-JAVA_RESULTS: "${{steps.pp1_1_test-java.outputs.result}}"
      with:
        runners: pp1_1_test-java
